#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# Show i3 info at a reasonable font size
xrandr --dpi 150x150

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

exec i3

# Cause screen to lock after 10 minutes
xautolock -time 10 -locker "i3exit lock" &

# Increase key repeat times
xset r rate 150 18

# Ignore trackpad input when typing
syndaemon -dt

[[ -f ~/.Xresources ]] && xrdb -load ~/.Xresources
