#!/usr/bin/env bash

. $COMMON_SCRIPTS/bash/utils/script_dir.sh

SCRIPT_DIR="$EXEC_DIR"
DIRENV_DIR="$SCRIPT_DIR"

VIRTUAL_ENVIRONMENT="$(echo "$1" | grep -o '^[a-zA-Z][a-zA-Z0-9._-]\+$')"
PYTHON_VERSION="$(echo "$1" | grep -o '^v\?[0-9.]\+$')"

if [[ -z "$VIRTUAL_ENVIRONMENT" ]]; then
  VIRTUAL_ENVIRONMENT="$(cat "$DIRENV_DIR/.virtual-environment" 2>/dev/null)"
fi

if [[ -z "$PYTHON_VERSION" ]] && [[ -z "$VIRTUAL_ENVIRONMENT" ]]; then
  PYTHON_VERSION="$(cat "$DIRENV_DIR/.python-version" 2>/dev/null)"
fi

is_python_version_installed() {
  pyenv versions | grep -q "^$PYTHON_VERSION\$"
}

install_missing_python_version() {
  pyenv install "$PYTHON_VERSION"
}

activate_python_version() {
  pyenv local "$PYTHON_VERSION"
}

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PYENV_ROOT=$HOME/.pyenv
export PATH="$PYENV_ROOT/bin:$PATH"

eval "$(pyenv init -)"

if [[ -n "$VIRTUAL_ENVIRONMENT" ]]; then
  pyenv activate "$VIRTUAL_ENVIRONMENT"
elif [[ -n "$PYTHON_VERSION" ]]; then
  if is_python_version_installed;  then
    if ! [[ "$(pyenv local)" == "$PYTHON_VERSION" ]];  then
      activate_python_version
    else
      echo "python version \`$PYTHON_VERSION\` already set"
    fi
  else
    install_missing_python_version
    activate_python_version
  fi
else
  echo "SKIP: install.  pyenv virtualenv $VIRTUAL_ENVIRONMENT is already installed"
fi
