#!/bin/bash
help() {
  cat <<-EOM
setup [-p | --peripheral] [-P | --no-peripheral]

Customize input setup

EOM
}

if [[ "$1" = '-h' || "$1" == '--help' ]]; then
  help
  exit 0
elif [[ "$1" = '-P' || "$1" == '--no-peripheral' ]]; then
  touchpad enable
elif [[ "$1" = '-p' || "$1" == '--peripheral' ]]; then
  touchpad disable
else
  touchpad disable
fi

touchpad sensitivity
mouse sensitivity
systemctl start --user sxhkd
mons -o
