#!/usr/bin/env bash
. ~/src/scripts/bash/utils/script_dir.sh

SCRIPT_DIR="$EXEC_DIR"

NVM_DIR="$HOME/.nvm"

EXPECTED_NODE_VERSION="$(echo "$1" | grep '^v\?[0-9.]\+$')"

if [[ -z "$EXPECTED_NODE_VERSION" ]]; then
  EXPECTED_NODE_VERSION="$(cat "$SCRIPT_DIR/.nvmrc")"
fi

EXPECTED_NODE_VERSION="v$(echo $EXPECTED_NODE_VERSION | grep -o '[0-9.]\+$')"

for v in "$NVM_DIR"/versions/node/*; do

  CANDIDATE_VERSION="$(echo $(basename $v) | grep "$EXPECTED_NODE_VERSION")"
  if [[ -n "$CANDIDATE_VERSION" ]]; then
    CHOSEN_VERSION="$CANDIDATE_VERSION"
  fi
done

NODE_BIN_PATH="$NVM_DIR/versions/node/$CHOSEN_VERSION/bin"


if [[ $(command -v "$NODE_BIN_PATH/node") ]]; then
  echo "Using node: $CHOSEN_VERSION ($(command -v "$NODE_BIN_PATH/node"))"
  export PATH="$NODE_BIN_PATH:$PATH"
else
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

  nvm install "$EXPECTED_NODE_VERSION"

  if ! command -v node || [[ "$(node --version)" != "$EXPECTED_NODE_VERSION" ]]; then
    nvm install "$EXPECTED_NODE_VERSION"
  fi
  nvm use
fi
