#!/bin/bash

export PYENV_VIRTUALENV_DISABLE_PROMPT=1
export PYENV_ROOT=$HOME/.pyenv
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv activate gcloud-sdk

~/src/vendor/google-cloud-sdk/bin/gcloud "$@"

pyenv deactivate
