#!/bin/bash

SEPARATOR='ก'

IFS= read -r -d '' JQ<<-EOF
  if (.errors != null and .errorMessages[0] != null)
  then .
  else
    .issues
    | .[]
    | "\(.key)
$SEPARATOR \(.fields.assignee.displayName)
$SEPARATOR \(.fields.priority.id | if . == "1" then "-2" else if . == "2" then "-1" else if . == "3" then " " else if . == "4" then "+1" else if . == "5" then "+2" else . end end end end end)
$SEPARATOR \(.fields.issuetype.name)
$SEPARATOR \"\(.fields.summary)\""
  end
EOF

JQ=${JQ//[[:space:]]/ }

jq -r "$JQ" | column -s "$SEPARATOR" -t

