#!/usr/bin/env bash
echo $'  Branch\tCommit\tMessage\tAuthor\tTime'
echo $'  ------\t------\t-------\t------\t----'
git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset)	%(color:red)%(objectname:short)%(color:reset)	%(contents:subject)	%(authorname)	(%(color:green)%(committerdate:relative)%(color:reset))'
