#!/bin/bash
set -e 
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "$SCRIPT_DIR/utils.sh"

project=$(find_upward "*.xcodeproj")
project_name="$(basename $project | cut -d '.' -f1)"
echo "PROJECT NAME: $project_name"
xcodebuild -project "$project" -scheme "$project_name"
