#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "$SCRIPT_DIR/utils.sh"

BUNDLE_NAME=$(get_build_setting "PRODUCT_BUNDLE_IDENTIFIER")
xcrun simctl launch booted "$BUNDLE_NAME" 
