#!/bin/bash
set -e 

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
"$SCRIPT_DIR/find" "$@" | jq -r '.name'
ID=$("$SCRIPT_DIR/find-id" "$@")
xcrun simctl shutdown "$ID" 
