#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "$SCRIPT_DIR/utils.sh"

PROJECT=$(find_project)
echo "$PROJECT"
BUNDLE_NAME="$(xcodebuild -project $PROJECT -showBuildSettings -json | jq -r '.[0] | .buildSettings | .PRODUCT_BUNDLE_IDENTIFIER')"

xcrun simctl uninstall booted "$BUNDLE_NAME"
