#!/bin/bash
set -eup
aws-mfa
AWS_PROFILE=mfa aws ecr get-login-password \
              --region us-east-1 \
          | /usr/local/bin/docker login \
              --username AWS \
              --password-stdin 082163301176.dkr.ecr.us-east-1.amazonaws.com

/usr/local/bin/docker login
