#!/bin/bash

if [[ $_ != $0 ]]; then
  SOURCED=1
else
  SOURCED=
fi

url_encode() {
    # urlencode <string>
    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C
    
    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%%%02X' "'$c" ;;
        esac
    done
    
    LC_COLLATE=$old_lc_collate
}

if [[ -z "$SOURCED" ]]; then
  if [ $# -gt 0 ]; then
    url_encode "$@"
  else
    while read line; do
      url_encode "$line"
    done < /dev/stdin
  fi
fi
