#!/bin/bash

CURRENT_DIR="$(pwd)"

BOLD=$(tput bold)
NORMAL=$(tput sgr0)

# Utility Functions
banner() {
  columns="$(tput cols)"
  printf "\n"
  printf "\n"
  printf "%b" "${BOLD}"
  printf "%0.s=" $(seq 1 $columns)
  printf "\n"
  echo "$*"
  printf "%0.s=" $(seq 1 $columns)
  printf "%b" "${NORMAL}"
}

echo_bold() {
  echo "${BOLD}$*${NORMAL}"
}

forEachDir() {
  COMMAND="$*"
  for r in */; do
    if [ -d "$r" ]; then
      cd "$r" || exit 1
      echo
      banner "$r"
      eval "${COMMAND}"
      cd "$CURRENT_DIR" || exit 1
    fi

  done
}

forEachDir "$*"
