#!/bin/bash
# https://github.com/koalman/shellcheck/wiki/SC1090

export EDITOR=/usr/local/bin/nvim

set -o vi
shopt -s globstar

PATH="$PATH:$HOME/bin"

sources=(
  "$HOME/src/scripts/install/prompt.sh"
  "$HOME/src/scripts/install/config_bash_history.sh"
  "$HOME/src/scripts/install/bash_aliases.sh"
  "$HOME/src/scripts/install/bash_functions.sh"
  "$HOME/src/scripts/install/git-completion.sh"
  "$HOME/src/scripts/install/hub.bash_completion.sh"
  "$HOME/src/scripts/install/dotfiles/bash/.bashrc"
)

for src in "${sources[@]}"; do
  # -s == if file exists and has size > 0
  if [[ -s $src ]]; then
    #shellcheck disable=1090
    source "$src"
  fi
done
