#!/bin/bash
. $HOME/.bash_profile
case $- in
  *i*) ;;
  *) return;;
esac

INSTALL_DIR="$HOME/src/scripts/install"

. "$INSTALL_DIR/lazy_sources/lazy_loader.sh"
# NVM
lazy_load 'nvm' "$LAZY_LOAD_DIR/nvm.sh"
debug_log "Lazy loaded: nvm"

# direnv
eval "$(direnv hook bash)"
debug_log "Loaded: direnv"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='ag -g "" | cut -d " " -f 2- | sort | uniq'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
debug_log "Lazy loaded: fzf"
