#!/bin/bash
# https://github.com/koalman/shellcheck/wiki/SC1090

export DEBUG_STARTUP=

VIM=$(which nvim)
if [ -z $VIM ]; then
  VIM=$(which vim)
fi

if [ -z $VIM ]; then
  VIM=$(which vi)
fi

export EDITOR=$VIM

set -o vi
set editing-mode vi
shopt -s globstar

PATH="$PATH:$HOME/bin"

INSTALL_DIR="$HOME/src/scripts/install"
COMPLETIONS_DIR="$HOME/src/scripts/bash/completions"

. "$INSTALL_DIR/bash_debug_functions.sh"

sources=(
  "$INSTALL_DIR/bash_debug_functions.sh"
  "$INSTALL_DIR/prompt.sh"
  "$INSTALL_DIR/config_bash.sh"
  "$INSTALL_DIR/config_bash_history.sh"
  "$INSTALL_DIR/bash_aliases.sh"
  "$INSTALL_DIR/bash_functions.sh"
  "$INSTALL_DIR/git-completion.sh"
  "$INSTALL_DIR/hub.bash_completion.sh"
  "$COMPLETIONS_DIR/pass/pass.bash-completions.sh"
)

for src in "${sources[@]}"; do
  # -s == if file exists and has size > 0
  if [[ -s $src ]]; then
    #shellcheck disable=1090
    . "$src"
    debug_log "Loaded: $src"
  fi
done
