#!/bin/bash
if [[ 0 -eq $# ]]; then
  while read line
  do
    args=("${args[@]}" $line)
  done
else
  args=( "$@" )
fi

TITLE=${args[0]}

CONTENT=("${args[@]:1}")

osascript -e "display notification \"${CONTENT[@]}\" with title \"$TITLE\""
