#!/bin/bash

SCRATCH_PATH="$HOME/.scratch_pad"

if [[ "$1" == "list" ]]; then
  ls $SCRATCH_PATH
  exit
fi

raw_string=$(printf '"%s "' "$@")
name=$(echo $raw_string | tr '[:upper:]' '[:lower:]'| tr ' ' '-' | tr -cd '[[:alnum:]]._-')
mkdir -p $SCRATCH_PATH
$EDITOR "$SCRATCH_PATH/scratch_$name"
