#!/usr/bin/env bash

"$HOME/.pyenv/versions/list-workspaces/bin/python" "$HOME/bin/list-workspaces.py" # | \
  # fzf --ansi | \
  # cut -d ' ' -f 1 | \
  # sed 's/\([0-9]\+\):\(.\)\(.\)/\1:\2<sub>\3<\/sub>/' | \
  # xargs -I'{}' i3-msg workspace {}
  # # rev | \
