#!/bin/bash
NODE_VERSION="$(cat "./.nvmrc")"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

function main() {

  if ! has_expected_node_version || ! is_node_version_installed; then
    echo "RUN: Install $NODE_VERSION"
    install_missing_nvm
    echo "RUN COMPLETE: Install $NODE_VERSION"
  else
    echo "SKIP: install.  node $NODE_VERSION is already installed"
  fi

}

has_expected_node_version() {
  command -v node && [[ "$(node --version)" != "$(cat "$SCRIPT_DIR/.nvmrc")" ]]; then
}

function is_node_version_installed() {
  nvm list | grep -q "$NODE_VERSION"
}


function install_missing_nvm() {
  nvm install "$NODE_VERSION"
}

main "$@"

nvm use
