#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

NVM_DIR="$HOME/.nvm"

EXPECTED_NODE_VERSION="$(cat "$SCRIPT_DIR/.nvmrc")"

NODE_BIN_PATH="$NVM_DIR/versions/node/$EXPECTED_NODE_VERSION/bin"
echo "$(command -v "$NODE_BIN_PATH/node")"

if [[ $(command -v "$NODE_BIN_PATH/node") ]]; then
  export PATH="$NODE_BIN_PATH:$PATH"
else
  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

  nvm install "$EXPECTED_NODE_VERSION"

  if ! command -v node || [[ "$(node --version)" != "$EXPECTED_NODE_VERSION" ]]; then
    nvm install "$EXPECTED_NODE_VERSION"
  fi
  nvm use
fi
